version: '3.7'

services:
  scooby-docker:
    image: base-development
    build: .
    container_name: utadeo-development
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix/:/tmp/.X11-unix 
      - .:/home/ws
    environment: 
      - ROS_DOMAIN_ID=25
      #- DISPLAY=$DISPLAY
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0" # ARM
    network_mode: "host"
    working_dir: /home/ws
    privileged: true
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash
